[project]
name = "ps2"
version = "0.1.0"
description = "Informed search and RRT homework"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "descartes>=1.1.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "networkx>=3.6.1",
    "pydot-ng>=2.0.0",
    "pyyaml>=6.0.2",
    "principles-of-autonomy",
    "shapely>=2.1.0",
]

[tool.uv.sources]
principles-of-autonomy = { path = "../.." }
